import { createFileRoute } from "@tanstack/react-router";
import type {} from "@tanstack/react-start";

export const Route = createFileRoute("/robots.txt")({
  server: {
    handlers: {
      GET: async () => {
        const body = [
          "# IBONA (Rebalive) — African-first video streaming",
          "# https://rebalive.egreedtech.org",
          "",
          "User-agent: *",
          "Allow: /",
          "Disallow: /auth",
          "Disallow: /studio",
          "Disallow: /upload",
          "Disallow: /settings",
          "Disallow: /profile",
          "Disallow: /search?",
          "",
          "# Explicit allow for high-value crawlers",
          "User-agent: Googlebot",
          "Allow: /",
          "",
          "User-agent: Googlebot-Video",
          "Allow: /",
          "",
          "User-agent: Googlebot-Image",
          "Allow: /",
          "",
          "User-agent: Bingbot",
          "Allow: /",
          "",
          "User-agent: DuckDuckBot",
          "Allow: /",
          "",
          "User-agent: Applebot",
          "Allow: /",
          "",
          "User-agent: Twitterbot",
          "Allow: /",
          "",
          "User-agent: facebookexternalhit",
          "Allow: /",
          "",
          "User-agent: LinkedInBot",
          "Allow: /",
          "",
          "# AI / LLM crawlers — allow for discovery",
          "User-agent: GPTBot",
          "Allow: /",
          "",
          "User-agent: OAI-SearchBot",
          "Allow: /",
          "",
          "User-agent: ChatGPT-User",
          "Allow: /",
          "",
          "User-agent: PerplexityBot",
          "Allow: /",
          "",
          "User-agent: Google-Extended",
          "Allow: /",
          "",
          "Sitemap: https://rebalive.egreedtech.org/sitemap.xml",
          "Sitemap: https://rebalive.egreedtech.org/sitemap-pages.xml",
          "Sitemap: https://rebalive.egreedtech.org/sitemap-videos.xml",
          "Sitemap: https://rebalive.egreedtech.org/sitemap-creators.xml",
          "",
        ].join("\n");
        return new Response(body, {
          headers: {
            "Content-Type": "text/plain; charset=utf-8",
            "Cache-Control": "public, max-age=3600",
          },
        });
      },
    },
  },
});
