/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapVideosDotxmlRouteImport } from './routes/sitemap-videos[.]xml'
import { Route as SitemapPagesDotxmlRouteImport } from './routes/sitemap-pages[.]xml'
import { Route as SitemapCreatorsDotxmlRouteImport } from './routes/sitemap-creators[.]xml'
import { Route as ShortsRouteImport } from './routes/shorts'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MusicRouteImport } from './routes/music'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchVideoIdRouteImport } from './routes/watch.$videoId'
import { Route as ImgSplatRouteImport } from './routes/img.$'
import { Route as CUsernameRouteImport } from './routes/c.$username'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapVideosDotxmlRoute = SitemapVideosDotxmlRouteImport.update({
  id: '/sitemap-videos.xml',
  path: '/sitemap-videos.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPagesDotxmlRoute = SitemapPagesDotxmlRouteImport.update({
  id: '/sitemap-pages.xml',
  path: '/sitemap-pages.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapCreatorsDotxmlRoute = SitemapCreatorsDotxmlRouteImport.update({
  id: '/sitemap-creators.xml',
  path: '/sitemap-creators.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortsRoute = ShortsRouteImport.update({
  id: '/shorts',
  path: '/shorts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchVideoIdRoute = WatchVideoIdRouteImport.update({
  id: '/watch/$videoId',
  path: '/watch/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ImgSplatRoute = ImgSplatRouteImport.update({
  id: '/img/$',
  path: '/img/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CUsernameRoute = CUsernameRouteImport.update({
  id: '/c/$username',
  path: '/c/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/movies': typeof MoviesRoute
  '/music': typeof MusicRoute
  '/profile': typeof ProfileRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/shorts': typeof ShortsRoute
  '/sitemap-creators.xml': typeof SitemapCreatorsDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-videos.xml': typeof SitemapVideosDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/trending': typeof TrendingRoute
  '/upload': typeof UploadRoute
  '/c/$username': typeof CUsernameRoute
  '/img/$': typeof ImgSplatRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/movies': typeof MoviesRoute
  '/music': typeof MusicRoute
  '/profile': typeof ProfileRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/shorts': typeof ShortsRoute
  '/sitemap-creators.xml': typeof SitemapCreatorsDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-videos.xml': typeof SitemapVideosDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/trending': typeof TrendingRoute
  '/upload': typeof UploadRoute
  '/c/$username': typeof CUsernameRoute
  '/img/$': typeof ImgSplatRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/movies': typeof MoviesRoute
  '/music': typeof MusicRoute
  '/profile': typeof ProfileRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/shorts': typeof ShortsRoute
  '/sitemap-creators.xml': typeof SitemapCreatorsDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-videos.xml': typeof SitemapVideosDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/trending': typeof TrendingRoute
  '/upload': typeof UploadRoute
  '/c/$username': typeof CUsernameRoute
  '/img/$': typeof ImgSplatRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/llms.txt'
    | '/movies'
    | '/music'
    | '/profile'
    | '/robots.txt'
    | '/search'
    | '/settings'
    | '/shorts'
    | '/sitemap-creators.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-videos.xml'
    | '/sitemap.xml'
    | '/studio'
    | '/trending'
    | '/upload'
    | '/c/$username'
    | '/img/$'
    | '/watch/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/llms.txt'
    | '/movies'
    | '/music'
    | '/profile'
    | '/robots.txt'
    | '/search'
    | '/settings'
    | '/shorts'
    | '/sitemap-creators.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-videos.xml'
    | '/sitemap.xml'
    | '/studio'
    | '/trending'
    | '/upload'
    | '/c/$username'
    | '/img/$'
    | '/watch/$videoId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/llms.txt'
    | '/movies'
    | '/music'
    | '/profile'
    | '/robots.txt'
    | '/search'
    | '/settings'
    | '/shorts'
    | '/sitemap-creators.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-videos.xml'
    | '/sitemap.xml'
    | '/studio'
    | '/trending'
    | '/upload'
    | '/c/$username'
    | '/img/$'
    | '/watch/$videoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  MoviesRoute: typeof MoviesRoute
  MusicRoute: typeof MusicRoute
  ProfileRoute: typeof ProfileRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  ShortsRoute: typeof ShortsRoute
  SitemapCreatorsDotxmlRoute: typeof SitemapCreatorsDotxmlRoute
  SitemapPagesDotxmlRoute: typeof SitemapPagesDotxmlRoute
  SitemapVideosDotxmlRoute: typeof SitemapVideosDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudioRoute: typeof StudioRoute
  TrendingRoute: typeof TrendingRoute
  UploadRoute: typeof UploadRoute
  CUsernameRoute: typeof CUsernameRoute
  ImgSplatRoute: typeof ImgSplatRoute
  WatchVideoIdRoute: typeof WatchVideoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-videos.xml': {
      id: '/sitemap-videos.xml'
      path: '/sitemap-videos.xml'
      fullPath: '/sitemap-videos.xml'
      preLoaderRoute: typeof SitemapVideosDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-pages.xml': {
      id: '/sitemap-pages.xml'
      path: '/sitemap-pages.xml'
      fullPath: '/sitemap-pages.xml'
      preLoaderRoute: typeof SitemapPagesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-creators.xml': {
      id: '/sitemap-creators.xml'
      path: '/sitemap-creators.xml'
      fullPath: '/sitemap-creators.xml'
      preLoaderRoute: typeof SitemapCreatorsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shorts': {
      id: '/shorts'
      path: '/shorts'
      fullPath: '/shorts'
      preLoaderRoute: typeof ShortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$videoId': {
      id: '/watch/$videoId'
      path: '/watch/$videoId'
      fullPath: '/watch/$videoId'
      preLoaderRoute: typeof WatchVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/img/$': {
      id: '/img/$'
      path: '/img/$'
      fullPath: '/img/$'
      preLoaderRoute: typeof ImgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$username': {
      id: '/c/$username'
      path: '/c/$username'
      fullPath: '/c/$username'
      preLoaderRoute: typeof CUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  MoviesRoute: MoviesRoute,
  MusicRoute: MusicRoute,
  ProfileRoute: ProfileRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  ShortsRoute: ShortsRoute,
  SitemapCreatorsDotxmlRoute: SitemapCreatorsDotxmlRoute,
  SitemapPagesDotxmlRoute: SitemapPagesDotxmlRoute,
  SitemapVideosDotxmlRoute: SitemapVideosDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudioRoute: StudioRoute,
  TrendingRoute: TrendingRoute,
  UploadRoute: UploadRoute,
  CUsernameRoute: CUsernameRoute,
  ImgSplatRoute: ImgSplatRoute,
  WatchVideoIdRoute: WatchVideoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
